baseURL = "https://momotaro98.github.io/"
languageCode = "en-us"
title = "Dig Sky"
theme = "ink" # Never change
paginate = 10  # Default showing num of posts in top page

copyright = "© momotaro98"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-165392475-1"

# disqusShortname = "ink-demo"

[params]
	subtitle = "Webエンジニアがひっそり語るぼやき"

	# favicon = ""

	# Optional 64x64 avatar image.
	# [momotaro98 Note] Qiita page icon link
	avatar = "https://pbs.twimg.com/profile_images/1248275936392269824/R7SvHgrz_400x400.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	# [momotaro98 Note] I don't understand featherIconsCDN
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/momotaro98"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/jhtarosan"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/shintaro-ikeda-8382b2118/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
