baseURL = "https://momotaro98.github.io/"
languageCode = "en-us"
title = "momotaro98 blog"
theme = "ink" # Never change
paginate = 5  # Default showing num of posts in top page

copyright = "© momotaro98"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# googleAnalytics = "UA-123-45"
# disqusShortname = "ink-demo"

[params]
	subtitle = "momotaro98's personal blog"

	# favicon = ""

	# Optional 64x64 avatar image.
	# [momotaro98 Note] Qiita page icon link
	avatar = "https://qiita-user-profile-images.imgix.net/https%3A%2F%2Fs3-ap-northeast-1.amazonaws.com%2Fqiita-image-store%2F0%2F91562%2F96046a37bf87d952eda27e1a5588a3837dd8ffdb%2Fx_large.png%3F1580226511?ixlib=rb-1.2.2&auto=compress%2Cformat&lossless=0&w=48&s=3dac90b0cda60417bbdb6e8212f35d23"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	# [momotaro98 Note] I don't understand featherIconsCDN
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/momotaro98"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/jhtarosan"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/shintaro-ikeda-8382b2118/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
